### ISSUE TITLE
warning ../package.json: No license field error Command "watch" not found.

### ISSUE THREAD

**Issue by aodrasa** [Feedox/chatgpt-plugins-playground#7]

**Comment by Livshitz** [comment]
Hey @aodrasa, what command did you run?

**Comment by Livshitz** [comment]
Ah, yeah the readme was not correct. Thank you for reporting 🙏
Try running `yarn start`. 
README updated with https://github.com/feedox/alt-gpt/commit/865692b80167ce2be41cea8a5dede945bd6d454e
